name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
